COMMON:
  save_collected: True
  num_layers: 8
  neurons_per_layer: 20

  TIMESTEP: 0.04 # 0.002 * 20
  TRAINFILE: train.csv
  TESTFILE: test.csv
  TESTSET_MULTIPLIER: 1 # |Trainset| = |Trainset|*multiplier

  ALL_MODEL_CONFIGS: [INTERNAL_O3_100, INTERNAL_O3_200, INTERNAL_O3_400, WEAK_FF_100, WEAK_FF_200, WEAK_FF_400]
  ALL_DATA_CONFIGS: [TOY_NOSTOP, TOY_HIGHSTOP, TOY_MIXED, SIMULATION_NOSTOP, SIMULATION_HIGHSTOP, SIMULATION_MIXED]

  MODEL_CONFIGS: [WEAK_FF_400]
  DATA_CONFIGS: [TOY_NOSTOP]
  NOISE_CONFIGS: [0.00]

  ALPHA: [0.01, 0.1, 1, 10, 100]

  SAVE_PLOT: True
  SAVE_MODEL: True
  DATASET_CACHING: False
  MODEL_CACHING: False

# MODEL CONFIGS
# differential_order - Tells the type of the differential equation used
# 1: x_t = v + acc*t
# 2: x_tt = acc
# 3. x_ttt = 0

BORDER_O1:
  model_name: border_o1
  training_is_border: True
  take_differential_points: True
  num_datadriven: 200
  num_collocation: 1000
  differential_order: 1

INTERNAL_O3_100:
  model_name: internal_o3_100
  training_is_border: False
  take_differential_points: True
  num_datadriven: 100
  num_collocation: 1000
  differential_order: 3

INTERNAL_O3_200:
  model_name: internal_o3_200
  training_is_border: False
  take_differential_points: True
  num_datadriven: 200
  num_collocation: 1000
  differential_order: 3

INTERNAL_O3_400:
  model_name: internal_o3_400
  training_is_border: False
  take_differential_points: True
  num_datadriven: 400
  num_collocation: 1000
  differential_order: 3

STRONG_FF:
  model_name: strong_ff
  training_is_border: False
  take_differential_points: False
  num_datadriven: 1200
  num_collocation: 0

WEAK_FF_100:
  model_name: weak_ff_100
  training_is_border: False
  take_differential_points: False
  num_datadriven: 100
  num_collocation: 0

WEAK_FF_200:
  model_name: weak_ff_200
  training_is_border: False
  take_differential_points: False
  num_datadriven: 200
  num_collocation: 0

WEAK_FF_400:
  model_name: weak_ff_400
  training_is_border: False
  take_differential_points: False
  num_datadriven: 2000
  num_collocation: 0

# DATA CONFIGS
# testdirs are which additional dirs to look for test files (in addition to the train dir)

TOY_NOSTOP:
  toy_data: True
  acc: -0.9

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 1.0
  TRAIN_VX_END: 20.0

  datadir: ./Data/toy_nostop/
  testdirs: []

TOY_HIGHSTOP:
  toy_data: True
  acc: -0.9

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 0.0
  TRAIN_VX_END: 3.0

  datadir: ./Data/toy_highstop/
  testdirs: []

TOY_MIXED:
  toy_data: True
  acc: -0.9

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 0.0
  TRAIN_VX_END: 45.0

  datadir: ./Data/toy_mixed/
  testdirs: [./Data/toy_nostop/, ./Data/toy_highstop/]

SIMULATION_NOSTOP:
  render: False
  save_debug: False
  toy_data: False
  acc: -0.3928519

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 40.0
  TRAIN_VX_END: 45.0

  datadir: ./Data/simulation_nostop/
  testdirs: []

SIMULATION_HIGHSTOP:
  render: False
  save_debug: False
  toy_data: False
  acc: -0.3928519

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 0.0
  TRAIN_VX_END: 3.0

  datadir: ./Data/simulation_highstop/
  testdirs: []

SIMULATION_MIXED:
  render: False
  save_debug: False
  toy_data: False
  acc: -0.3928519

  TRAIN_ITERATIONS: 1000
  TRAIN_VX_VALUES: 20
  TRAIN_VX_START: 0.0
  TRAIN_VX_END: 45.0

  datadir: ./Data/simulation_mixed/
  testdirs: [./Data/simulation_nostop/, ./Data/simulation_highstop/]
