COMMON:
  save_collected: True
  num_layers: 8
  neurons_per_layer: 20
  num_validation: 1000
  batch_size: 64
  ood_delta: 1.5
  noise: 0.05

  TIMESTEP: 0.004 # 0.002 * 20
  datafile: data.csv
  oodfile: ood.csv

  GENERATE_DATA: True
  GENERATE_OOD: True

  MODEL_CONFIGS: [BORDER_O1, INTERNAL_O3, WEAK_FF]
  DATA_CONFIGS: [TOY_NOSTOP, TOY_STOP, SIMULATION_NOSTOP, SIMULATION_STOP]
  NOISE_CONFIGS: [0.00, 0.01, 0.02, 0.05]

  SAVE_PLOT: True
  SAVE_MODEL: True

# MODEL CONFIGS
# differential_order - Tells the type of the differential equation used
# 1: x_t = v + acc*t
# 2: x_tt = acc
# 3. x_ttt = 0

BORDER_O1:
  model_name: border_o1
  training_is_border: True
  take_differential_points: True
  num_datadriven: 200
  num_collocation: 1000
  differential_order: 1

INTERNAL_O3:
  model_name: internal_o3
  training_is_border: False
  take_differential_points: True
  num_datadriven: 200
  num_collocation: 1000
  differential_order: 3

STRONG_FF:
  model_name: strong_ff
  training_is_border: False
  take_differential_points: False
  num_datadriven: 1200
  num_collocation: 0

WEAK_FF:
  model_name: weak_ff
  training_is_border: False
  take_differential_points: False
  num_datadriven: 200
  num_collocation: 0

# DATA CONFIGS

TOY_NOSTOP:
  toy_data: True
  TOTAL_ITERATIONS: 1000
  VX_VALUES: 20
  VX_START: 0.1
  VX_END: 1.1
  acc: -0.0005
  datadir: ./Data/toy_nostop/

TOY_STOP:
  toy_data: True
  TOTAL_ITERATIONS: 1000
  VX_VALUES: 20
  VX_START: 0.0
  VX_END: 1.0
  acc: -0.05
  datadir: ./Data/toy_stop/

SIMULATION_NOSTOP:
  render: False
  save_debug: False
  toy_data: False
  acc: -0.3928519
  TOTAL_ITERATIONS: 40
  VX_VALUES: 500
  VX_START: 1.5
  VX_END: 2.5
  datadir: ./Data/simulation_nostop/

SIMULATION_STOP:
  render: False
  save_debug: False
  toy_data: False
  acc: -0.3928519
  TOTAL_ITERATIONS: 1000
  VX_VALUES: 20
  VX_START: 0.0
  VX_END: 1.0
  datadir: ./Data/simulation_stop/
