ACTIVE: ARTIFICIAL_STOP

COMMON:
  save_collected: True
  training_is_border: True
  take_differential_points: True
  num_datadriven: 200
  num_collocation: 1000
  num_layers: 8
  neurons_per_layer: 20
  num_validation: 1000
  batch_size: 64

  ### Tells the type of the differential equation used
  ### 1: x_t = v + acc*t
  ### 2: x_tt = acc
  ### 3. x_ttt = 0

  differential_order: 3
  TIMESTEP: 0.004 # 0.002 * 20

ARTIFICIAL_NOSTOP:
  artificial_data: True
  TOTAL_ITERATIONS: 1000
  V_VALUES: 20
  acc: -0.0005
  VX_DELTA: 0.1
  filename: ./Data/data_artificial_nostop.csv

ARTIFICIAL_STOP:
  artificial_data: True
  TOTAL_ITERATIONS: 1000
  V_VALUES: 20
  acc: -0.05
  filename: ./Data/data_artificial_stop.csv

SIMULATION_NOSTOP:
  render: False
  save_debug: False
  artificial_data: False
  acc: -0.3928519
  TOTAL_ITERATIONS: 40
  V_VALUES: 500
  VX_DELTA: 1.5
  filename: ./Data/data_simulation_nostop.csv

SIMULATION_STOP:
  render: False
  save_debug: False
  artificial_data: False
  acc: -0.3928519
  TOTAL_ITERATIONS: 1000
  V_VALUES: 20
  filename: ./Data/data_simulation_stop.csv
